# Generated by Django 3.2.8 on 2021-10-19 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_chatmessage_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code',
            new_name='PrivateCode',
        ),
        migrations.CreateModel(
            name='PublicCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_username', models.CharField(default='', max_length=100)),
                ('room_code', models.CharField(max_length=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
