# Generated by Django 3.2.8 on 2021-10-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20211019_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiccode',
            name='room_type',
            field=models.CharField(default='public', max_length=6),
        ),
    ]
