# Generated by Django 3.2.8 on 2021-10-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_publiccode_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publiccode',
            name='room_type',
        ),
    ]
