# Generated by Django 3.2.8 on 2021-10-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_publiccode_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatecode',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='publiccode',
            name='owner',
        ),
    ]
