# Generated by Django 3.2.8 on 2021-10-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_auto_20211019_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='room_type',
            field=models.CharField(default='', max_length=7),
        ),
    ]
