# Generated by Django 3.2.6 on 2021-11-23 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_auto_20211123_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='author',
            new_name='user',
        ),
    ]
