# Generated by Django 3.2.6 on 2021-11-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_rename_author_chatmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='author',
            field=models.TextField(default='abcd'),
            preserve_default=False,
        ),
    ]
