# Generated by Django 3.2.6 on 2021-11-23 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_auto_20211123_0848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
