# Generated by Django 3.2.6 on 2021-11-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='canvas_data_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='author',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
