# Generated by Django 3.2.6 on 2021-11-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0015_auto_20211123_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='canvas_data_url',
            field=models.TextField(default='none'),
        ),
    ]
