# Generated by Django 3.2.8 on 2021-11-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0016_alter_room_canvas_data_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
