# Generated by Django 3.2.8 on 2021-11-25 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0017_room_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owner_username',
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(related_name='players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='word',
            field=models.CharField(default='', max_length=100),
        ),
    ]
