# Generated by Django 3.2.8 on 2021-11-25 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0019_room_current_playe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='current_playe',
            new_name='current_player',
        ),
    ]
