# Generated by Django 3.2.8 on 2021-11-25 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0020_rename_current_playe_room_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='timer',
            field=models.TimeField(default=datetime.time(0, 0, 59)),
        ),
    ]
