# Generated by Django 3.2.8 on 2021-11-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0025_alter_score_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='round_no',
            field=models.IntegerField(default=0),
        ),
    ]
