# Generated by Django 3.2.8 on 2021-11-26 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0026_room_round_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='players',
        ),
        migrations.AddField(
            model_name='room',
            name='done_players',
            field=models.ManyToManyField(related_name='done_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='rem_players',
            field=models.ManyToManyField(related_name='rem_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_player',
            field=models.ForeignKey(on_delete=models.SET(models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)), related_name='current_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
