# Generated by Django 3.2.8 on 2021-11-26 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0027_auto_20211127_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guessed',
            field=models.ManyToManyField(related_name='guessed', to=settings.AUTH_USER_MODEL),
        ),
    ]
