# Generated by Django 3.2.9 on 2021-11-28 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0028_room_guessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='kickers',
            field=models.ManyToManyField(related_name='kickers', to=settings.AUTH_USER_MODEL),
        ),
    ]
